kind: Service
apiVersion: v1
metadata:
  name: spring-boot-hello
spec:
  type: LoadBalancer
  selector:
    app: spring-boot-hello
  ports:
    - name: http
      protocol: TCP
      # ELB's port
      port: 8080
